website: Fixed a compile error.
Per [1], `sim_objects` is now a mandatory parameter. This change
reflects that change.

Without this change, the following compilation error will occur,

Error: SimObject(HelloObject.py...) must list c++ sim_objects or
enums (set either to [] if there are none).

[1] https://gem5-review.googlesource.com/c/public/gem5/+/54203

Change-Id: I24fa7489c08bc1cae597455b9f74a48dafdb9d01
Reviewed-on: https://gem5-review.googlesource.com/c/public/gem5-website/+/59211
Tested-by: Bobby Bruce <bbruce@ucdavis.edu>
Reviewed-by: Bobby Bruce <bbruce@ucdavis.edu>
Maintainer: Bobby Bruce <bbruce@ucdavis.edu>